# Generated by Django 6.0.6 on 2026-07-26 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('company', models.CharField(max_length=300)),
                ('salary', models.CharField(max_length=300)),
                ('job_type', models.CharField(max_length=200)),
                ('Employment_type', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('deadline', models.CharField(max_length=500)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
