# Generated by Django 6.0.6 on 2026-07-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.CharField(max_length=500),
        ),
    ]
